---

- hosts: localhost

  tasks:

  # 1st task to be placed here is to read Org name, Project/Application name, other devops action details from UI (passed as --extra-vars to this playbook) where project/appname can be used as a PublicKey. Imp point here is this Playbook will be called from Python app.py API webmethod (say /startup) which will run azurelogin.sh script that will open the az login interactively on Browser and once user logs in then response from python subprocess will collect username, orgname and then render_html 2nd page that will take user inputs (like project/appname, what action they need to do etc.)  & autopopulates the orgname (captured in 1st subprocess call of azurelogin script). Once submit from 2nd page is done then This playbook will be called with orgname, project/appname etc as --extra-vars
  # This PublicKey will be used to search in Azure MySQL DB/Table=azureMappingVault as if it exists or not. 
  # If yes, then pull the associated ServicePrincipalName, ClientID, TenantID, ObjectID & Secret. For One project/appname = Only One ServicePrincipal ids & secret will be generated (by admin). 
  # If project/appname doesn't exist then send mail to genpact Admin user (in next task) asking to login to Onboarding OneUI & create/provision ServicePrincipals, Secrets for that project/appname/team that will trigger adminuser playbook which will save projectname/appname, SP, ClientID, ClientSecret, TenantID, ObjectID, OrgName, resourcegroupname in DB & Vault respectively. After snding mail from next task terminate the playbook using When condition & let user know to contact Admin user for onboarding formalities 
  # If projectname/appname was found in Azure DB, then pull the secrets, SP name etc. to login as SP for framework to proceed with DevOps OOB provisioning tasks. This can be done by calling remoteCall API that will take care of signing in as SP & thereafter trigger the DevOps tasks as per inputs by User taken or passed to this playbook as --extra-vars 


  - name: Framework is trying to login with ServicePrincipalName on behalf of the Customer
    shell: "echo az login --service-principal --username {{ clientID | default('') }} --password {{ clientSecret | default('') }} --tenant {{ tenantID | default('') }}"
    register: servicePrincipalLoginOut
  - debug: var=servicePrincipalLoginOut.stdout


  - name: Good to add Azure DevOps extension(or, upgrade if already added)
    shell: "az extension add --upgrade -n azure-devops"
    register: azureDevOpsExtOut
  - debug: var=azureDevOpsExtOut.stdout


  - name: Login to Azure DevOps using Org's PAT tokens
    shell: "echo -n {{ pat | default('') }} | az devops login --organization https://dev.azure.com/{{ devopsOrgName | default('') }}"
    register: azureDevOpsPATLoginOut
  - debug: var=azureDevOpsPATLoginOut.stdout

 
  #- name: Configure defaults to set the configuration for the organization and project
    #shell: "az devops project show --project {{ devopsProject | default('') }}"
    #register: azureDevOpsProjectCheckOut
  #- debug: var=azureDevOpsProjectCheckOut


  # To be run if output of above task is not "TF200016: The following project does not exist" in azureDevOpsProjectCheckOut.stdout variable
  - name: Creating DevOps project on Azure DevOps Server
    shell: "az devops project create --name {{ devopsProject | default('') }}"
    register: azureDevOpsProjectCreateOut
    when: ( DevOpsPipelineActions != "runpipeline" and DevOpsPipelineActions != "deletepipeline" and DevOpsPipelineActions != "updatepipeline" )
  - debug: var=azureDevOpsProjectCreateOut.stdout

  - name: Configure defaults to set the configuration for the organization and project
    shell: "az devops configure --defaults organization=https://dev.azure.com/{{ devopsOrgName | default('') }} project={{ devopsProject | default('') }}"
    register: devopsConfigureOut
  - debug: var=devopsConfigureOut.stdout


  # To be run if devops action is to create a pipeline
  - name: Configure defaults to set the configuration for the organization and project
    shell: "export AZURE_DEVOPS_EXT_GITHUB_PAT=d73c4c3febbd2fa9a938515239b7b094cef4fa68aa && az devops service-endpoint github create --github-url {{ Repository | default('') }} --name \"GitHubServiceConnection\" | grep -A 2 -i 'groupScopeId' | grep \"id\" |  sed 's/\"id\": //g' | sed 's/\"//g' | sed 's/,//g' | sed 's/^ *//g'"
    register: GitHubServiceConnectionIDOut
  - debug: var=GitHubServiceConnectionIDOut.stdout

 
  - set_fact: GitHubServiceConnectionIDGlobal = "{{ GitHubServiceConnectionIDOut.stdout }}"   
    register: GitHubServiceConnectionIDGlobal

  # To be triggered if Pipeline needs to be setup/created (for dotnetcore application)
  - name: Create the automated Azure DevOps pipeline by referencing the azure-pipelines.yml
    shell: "az pipelines create --name {{ devopsProject | default('') }}.CI --description 'Pipeline setup for the .Net project' --repository {{ Repository | default('') }} --branch master --yml-path azure-pipelines.yml --service-connection {{ GitHubServiceConnectionIDOut.stdout }}"
    register: createDotNetCorePipelineOut
    when: ( ProjectStack == "dotnetcore" and DevOpsPipelineActions == "createpipeline" )
  - debug: var=createDotNetCorePipelineOut.stdout


  # To be triggered if Pipeline needs to be setup/created (for Java application)
  - name: Create the automated Azure DevOps pipeline by referencing the azure-pipelines.yml
    shell: "az pipelines create --name {{ devopsProject | default('') }}.CI --description 'Pipeline setup for the Java project' --repository {{ Repository | default('') }} --branch master --yml-path azure-pipelines.yml --service-connection {{ GitHubServiceConnectionIDOut.stdout }}"
    register: createJavaPipelineOut
    when: ( ProjectStack == "java" and DevOpsPipelineActions == "createpipeline" )
  - debug: var=createJavaPipelineOut.stdout


  # To be triggered if Pipeline needs to be setup/created (for Python application)
  - name: Create the automated Azure DevOps pipeline by referencing the azure-pipelines.yml
    shell: "az pipelines create --name {{ devopsProject | default('') }}.CI --description 'Pipeline setup for the Python project' --repository {{ Repository | default('') }} --branch master --yml-path azure-pipelines.yml --service-connection {{ GitHubServiceConnectionIDOut.stdout }}"
    register: createPythonPipelineOut
    when: ( ProjectStack == "python" and DevOpsPipelineActions == "createpipeline" )
  - debug: var=createPythonPipelineOut.stdout


  # To be triggered if Pipeline needs to be run thus first fetch all associated pipelins with a particular project
  - name: Fetch the automated Azure DevOps pipeline by referencing the project name
    shell: "az pipelines list --project {{ devopsProject | default('') }} | grep \"id\\|name\" | awk -F\",\" '{a=a $1; b=b $2} END{print a b}' | sed 's/^ *//g' | awk -F\" \" '{print $4\"#\"$6}' | sed 's/\"//g'"
    register: fetchPipelineOut
    when: ( (DevOpsPipelineActions == "runpipeline" or DevOpsPipelineActions == "updatepipeline" or DevOpsPipelineActions == "deletepipeline") and PipelineName == "" )
  - debug: var=fetchPipelineOut.stdout

  # To be triggered if Pipeline needs to be run for a particular project
  - name: Fetch PipelineID for performing delete or update operations on the automated Azure DevOps pipeline
    shell: "echo {{ PipelineName | default('') }} | awk -F\"#\" '{print $1}'"
    register: PipelineFilterIDOut
    when: ( (DevOpsPipelineActions == "deletepipeline" or DevOpsPipelineActions == "updatepipeline") and PipelineName != "" )
  - debug: var=PipelineFilterIDOut.stdout

  # To be triggered if Pipeline needs to be run for a particular project
  - name: Fetch PipelineID for performing run operation on the automated Azure DevOps pipeline
    shell: "echo {{ PipelineName | default('') }} | awk -F\"#\" '{print $2}'"
    register: runPipelineFilterIDOut
    when: ( DevOpsPipelineActions == "runpipeline" and PipelineName != "" )
  - debug: var=runPipelineFilterIDOut.stdout

  # To be triggered if Pipeline needs to be run for a particular project
  - name: Trigger the automated Azure DevOps pipeline by referencing the project name
    shell: "az pipelines run --name {{ runPipelineFilterIDOut.stdout | default('') }} --project {{ devopsProject | default('') }}"
    register: runPipelineOut
    when: ( DevOpsPipelineActions == "runpipeline" and PipelineName != "" )
  - debug: var=runPipelineOut.stdout

  # To be triggered if Pipeline needs to be deleted for a particular project
  - name: Delete the automated Azure DevOps pipeline by referencing the project name
    shell: "az pipelines delete --id {{ PipelineFilterIDOut.stdout | default('') }} --project {{ devopsProject | default('') }} --yes"
    register: deletePipelineOut
    when: ( DevOpsPipelineActions == "deletepipeline" and PipelineName != "" )
  - debug: var=deletePipelineOut.stdout

  # To be triggered if Pipeline needs to be updated for a particular project
  - name: Update the automated Azure DevOps pipeline by referencing the project name
    shell: "az pipelines update --id {{ PipelineFilterIDOut.stdout | default('') }} --new-name {{ NewPipelineName | default('devopspipeline.CI') }} --description {{ NewDescription | default('This_is_the_DevOps_Pipeline_Generated_By_Automation') }} --branch {{ NewBranch | default('master') }}"
    register: updatePipelineOut
    when: ( DevOpsPipelineActions == "updatepipeline" and PipelineName != "" )
  - debug: var=updatePipelineOut.stdout

  - name: Create Azure Boards with new Work Item as task to configure for associated devops project for changes tracking purposes
    shell: "az boards work-item create --title 'Creating new Task work item to track new operation being performed as mentioned in the description' --type 'Task' --description \"action is {{ DevOpsPipelineActions | default('') }} and project is {{ devopsProject | default('') }}\"  | grep 'url' | grep 'workItems' | sed 's/://g' | sed 's/url//g' | sed 's/\"//g' | sed 's/$ *//g'"
    register: createBoardsOut
  - debug: var=createBoardsOut.stdout
   